In [118]:
# Loading data
import pandas as pd
df_train = pd.read_csv('./data/train.csv')
df_test = pd.read_csv('./data/test.csv')
df_train.head()

,Id,AB,AF,AH,AM,AR,AX,AY,AZ,BC,...,FL,FR,FS,GB,GE,GF,GH,GI,GL,Class
0,000ff2bfdfe9,0.209377,3109.03329,85.200147,22.394407,8.138688,0.699861,0.025578,9.812214,5.555634,...,7.298162,1.73855,0.094822,11.339138,72.611063,2003.810319,22.136229,69.834944,0.120343,1
1,007255e47698,0.145282,978.76416,85.200147,36.968889,8.138688,3.632190,0.025578,13.517790,1.229900,...,0.173229,0.49706,0.568932,9.292698,72.611063,27981.562750,29.135430,32.131996,21.978000,0
2,013f2bd269f5,0.470030,2635.10654,85.200147,32.360553,8.138688,6.732840,0.025578,12.824570,1.229900,...,7.709560,0.97556,1.198821,37.077772,88.609437,13676.957810,28.022851,35.192676,0.196941,0
3,043ac50845d5,0.252107,3819.65177,120.201618,77.112203,8.138688,3.685344,0.025578,11.053708,1.229900,...,6.122162,0.49706,0.284466,18.529584,82.416803,2094.262452,39.948656,90.493248,0.155829,0
4,044fb8a146ec,0.380297,3733.04844,85.200147,14.103738,8.138688,3.942255,0.054810,3.396778,102.151980,...,8.153058,48.50134,0.121914,16.408728,146.109943,8524.370502,45.381316,36.262628,0.096614,1

In [119]:
df_train.drop(['Id'],axis=1,inplace=True)
df_train.head()

,AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD,...,FL,FR,FS,GB,GE,GF,GH,GI,GL,Class
0,0.209377,3109.03329,85.200147,22.394407,8.138688,0.699861,0.025578,9.812214,5.555634,4126.58731,...,7.298162,1.73855,0.094822,11.339138,72.611063,2003.810319,22.136229,69.834944,0.120343,1
1,0.145282,978.76416,85.200147,36.968889,8.138688,3.632190,0.025578,13.517790,1.229900,5496.92824,...,0.173229,0.49706,0.568932,9.292698,72.611063,27981.562750,29.135430,32.131996,21.978000,0
2,0.470030,2635.10654,85.200147,32.360553,8.138688,6.732840,0.025578,12.824570,1.229900,5135.78024,...,7.709560,0.97556,1.198821,37.077772,88.609437,13676.957810,28.022851,35.192676,0.196941,0
3,0.252107,3819.65177,120.201618,77.112203,8.138688,3.685344,0.025578,11.053708,1.229900,4169.67738,...,6.122162,0.49706,0.284466,18.529584,82.416803,2094.262452,39.948656,90.493248,0.155829,0
4,0.380297,3733.04844,85.200147,14.103738,8.138688,3.942255,0.054810,3.396778,102.151980,5728.73412,...,8.153058,48.50134,0.121914,16.408728,146.109943,8524.370502,45.381316,36.262628,0.096614,1

In [120]:
print(df_train.shape)
print(df_test.shape)

(617, 57)
(5, 57)

In [121]:
df_train.isna().sum()

AB        0
AF        0
AH        0
AM        0
AR        0
AX        0
AY        0
AZ        0
BC        0
BD        0
BN        0
BP        0
BQ       60
BR        0
BZ        0
CB        2
CC        3
CD        0
CF        0
CH        0
CL        0
CR        0
CS        0
CU        0
CW        0
DA        0
DE        0
DF        0
DH        0
DI        0
DL        0
DN        0
DU        1
DV        0
DY        0
EB        0
EE        0
EG        0
EH        0
EJ        0
EL       60
EP        0
EU        0
FC        1
FD        0
FE        0
FI        0
FL        1
FR        0
FS        2
GB        0
GE        0
GF        0
GH        0
GI        0
GL        1
Class     0
dtype: int64

In [122]:
df_train_phase1 = df_train.dropna()

In [123]:
df_test_phase1 = df_test.dropna()

In [124]:
print(df_train_phase1['EJ'].unique())
print(df_test_phase1['EJ'].unique())

['B' 'A']
['A']

In [125]:
train_dummies = pd.get_dummies(df_train_phase1.EJ, dtype='i')
test_dummies = pd.get_dummies(df_test_phase1.EJ, dtype='i')
train_dummies['EJ_A'] = train_dummies['A']
test_dummies['EJ_A'] = test_dummies['A']
train_dummies.head()

   A  B  EJ_A
0  0  1     0
1  1  0     1
2  0  1     0
3  0  1     0
4  0  1     0

In [126]:
test_dummies.head(2)

   A  EJ_A
0  1     1
1  1     1

In [127]:
df_train_phase2 = pd.concat([df_train_phase1,train_dummies['EJ_A']], axis='columns')
df_test_phase2 = pd.concat([df_test_phase1,test_dummies['EJ_A']], axis='columns')
df_train_phase2.head()

,AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD,...,FR,FS,GB,GE,GF,GH,GI,GL,Class,EJ_A
0,0.209377,3109.03329,85.200147,22.394407,8.138688,0.699861,0.025578,9.812214,5.555634,4126.58731,...,1.73855,0.094822,11.339138,72.611063,2003.810319,22.136229,69.834944,0.120343,1,0
1,0.145282,978.76416,85.200147,36.968889,8.138688,3.632190,0.025578,13.517790,1.229900,5496.92824,...,0.49706,0.568932,9.292698,72.611063,27981.562750,29.135430,32.131996,21.978000,0,1
2,0.470030,2635.10654,85.200147,32.360553,8.138688,6.732840,0.025578,12.824570,1.229900,5135.78024,...,0.97556,1.198821,37.077772,88.609437,13676.957810,28.022851,35.192676,0.196941,0,0
3,0.252107,3819.65177,120.201618,77.112203,8.138688,3.685344,0.025578,11.053708,1.229900,4169.67738,...,0.49706,0.284466,18.529584,82.416803,2094.262452,39.948656,90.493248,0.155829,0,0
4,0.380297,3733.04844,85.200147,14.103738,8.138688,3.942255,0.054810,3.396778,102.151980,5728.73412,...,48.50134,0.121914,16.408728,146.109943,8524.370502,45.381316,36.262628,0.096614,1,0

In [128]:
df_train_phase2.drop(['EJ'], axis=1, inplace=True)
df_test_phase2.drop(['EJ'], axis=1, inplace=True)
df_train_phase2.head()

,AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD,...,FR,FS,GB,GE,GF,GH,GI,GL,Class,EJ_A
0,0.209377,3109.03329,85.200147,22.394407,8.138688,0.699861,0.025578,9.812214,5.555634,4126.58731,...,1.73855,0.094822,11.339138,72.611063,2003.810319,22.136229,69.834944,0.120343,1,0
1,0.145282,978.76416,85.200147,36.968889,8.138688,3.632190,0.025578,13.517790,1.229900,5496.92824,...,0.49706,0.568932,9.292698,72.611063,27981.562750,29.135430,32.131996,21.978000,0,1
2,0.470030,2635.10654,85.200147,32.360553,8.138688,6.732840,0.025578,12.824570,1.229900,5135.78024,...,0.97556,1.198821,37.077772,88.609437,13676.957810,28.022851,35.192676,0.196941,0,0
3,0.252107,3819.65177,120.201618,77.112203,8.138688,3.685344,0.025578,11.053708,1.229900,4169.67738,...,0.49706,0.284466,18.529584,82.416803,2094.262452,39.948656,90.493248,0.155829,0,0
4,0.380297,3733.04844,85.200147,14.103738,8.138688,3.942255,0.054810,3.396778,102.151980,5728.73412,...,48.50134,0.121914,16.408728,146.109943,8524.370502,45.381316,36.262628,0.096614,1,0

In [129]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [130]:
for column in df_train_phase2.columns:
    if column != 'Class' and column != 'EJ_A':
        scaler.fit(df_train_phase2[[column]])
        df_train_phase2[column] = scaler.transform(df_train_phase2[[column]])
        df_test_phase2[column] = scaler.transform(df_test_phase2[[column]])
df_train_phase2.head()

,AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD,...,FR,FS,GB,GE,GF,GH,GI,GL,Class,EJ_A
0,0.028487,0.102347,0.00000,0.030632,0.0,0.000000,0.000000,0.180337,0.002958,0.047364,...,0.000998,0.000866,0.049385,0.000000,0.013846,0.176983,0.362261,0.005425,1,0
1,0.013752,0.027589,0.00000,0.053864,0.0,0.078048,0.000000,0.284500,0.000000,0.074042,...,0.000000,0.016014,0.033753,0.000000,0.194527,0.274495,0.164135,1.000000,0,1
2,0.088409,0.085715,0.00000,0.046519,0.0,0.160575,0.000000,0.265013,0.000000,0.067011,...,0.000385,0.036139,0.246003,0.011229,0.095035,0.258994,0.180218,0.008910,0,0
3,0.038310,0.127285,0.01918,0.117854,0.0,0.079462,0.000000,0.215235,0.000000,0.048203,...,0.000000,0.006925,0.104313,0.006882,0.014475,0.425143,0.470820,0.007039,0,0
4,0.067780,0.124246,0.00000,0.017417,0.0,0.086300,0.002841,0.000000,0.069008,0.078555,...,0.038597,0.001731,0.088112,0.051588,0.059198,0.500829,0.185841,0.004345,1,0

In [131]:
x = df_train_phase2.drop(['Class'], axis=1)
x.head()

,AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD,...,FL,FR,FS,GB,GE,GF,GH,GI,GL,EJ_A
0,0.028487,0.102347,0.00000,0.030632,0.0,0.000000,0.000000,0.180337,0.002958,0.047364,...,0.051720,0.000998,0.000866,0.049385,0.000000,0.013846,0.176983,0.362261,0.005425,0
1,0.013752,0.027589,0.00000,0.053864,0.0,0.078048,0.000000,0.284500,0.000000,0.074042,...,0.000000,0.000000,0.016014,0.033753,0.000000,0.194527,0.274495,0.164135,1.000000,1
2,0.088409,0.085715,0.00000,0.046519,0.0,0.160575,0.000000,0.265013,0.000000,0.067011,...,0.054706,0.000385,0.036139,0.246003,0.011229,0.095035,0.258994,0.180218,0.008910,0
3,0.038310,0.127285,0.01918,0.117854,0.0,0.079462,0.000000,0.215235,0.000000,0.048203,...,0.043183,0.000000,0.006925,0.104313,0.006882,0.014475,0.425143,0.470820,0.007039,0
4,0.067780,0.124246,0.00000,0.017417,0.0,0.086300,0.002841,0.000000,0.069008,0.078555,...,0.057926,0.038597,0.001731,0.088112,0.051588,0.059198,0.500829,0.185841,0.004345,0

In [132]:
y = df_train_phase2['Class']
y.head()

0    1
1    0
2    0
3    0
4    1
Name: Class, dtype: int64

In [133]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=5)

In [134]:
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(25, input_shape=(56,)),
    keras.layers.LeakyReLU(alpha=0.2),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(10),
    keras.layers.LeakyReLU(alpha=0.3),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(5),
    keras.layers.LeakyReLU(alpha=0.3),
    keras.layers.Dense(1,activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
) 
model.fit(x_train,y_train, epochs=100)

Epoch 1/100
14/14 [==============================] - 1s 32ms/step - loss: 0.7544 - accuracy: 0.2763
Epoch 2/100
14/14 [==============================] - 0s 11ms/step - loss: 0.6617 - accuracy: 0.6918
Epoch 3/100
14/14 [==============================] - 0s 11ms/step - loss: 0.6110 - accuracy: 0.7945
Epoch 4/100
14/14 [==============================] - 0s 9ms/step - loss: 0.5662 - accuracy: 0.8037
Epoch 5/100
14/14 [==============================] - 0s 8ms/step - loss: 0.5199 - accuracy: 0.8037
Epoch 6/100
14/14 [==============================] - 0s 8ms/step - loss: 0.5030 - accuracy: 0.8037
Epoch 7/100
14/14 [==============================] - 0s 8ms/step - loss: 0.4925 - accuracy: 0.8037
Epoch 8/100
14/14 [==============================] - 0s 8ms/step - loss: 0.4871 - accuracy: 0.8037
Epoch 9/100
14/14 [==============================] - 0s 8ms/step - loss: 0.4664 - accuracy: 0.8059
Epoch 10/100
14/14 [==============================] - 0s 7ms/step - loss: 0.4732 - accuracy: 0.8059
Epoch 11/100
14/14 [==============================] - 0s 8ms/step - loss: 0.4764 - accuracy: 0.8059
Epoch 12/100
14/14 [==============================] - 0s 7ms/step - loss: 0.4559 - accuracy: 0.8059
Epoch 13/100
14/14 [==============================] - 0s 7ms/step - loss: 0.4368 - accuracy: 0.8128
Epoch 14/100
14/14 [==============================] - 0s 7ms/step - loss: 0.4272 - accuracy: 0.8174
Epoch 15/100
14/14 [==============================] - 0s 11ms/step - loss: 0.4096 - accuracy: 0.8265
Epoch 16/100
14/14 [==============================] - 0s 7ms/step - loss: 0.4078 - accuracy: 0.8402
Epoch 17/100
14/14 [==============================] - 0s 7ms/step - loss: 0.3648 - accuracy: 0.8584
Epoch 18/100
14/14 [==============================] - 0s 7ms/step - loss: 0.3757 - accuracy: 0.8562
Epoch 19/100
14/14 [==============================] - 0s 7ms/step - loss: 0.3478 - accuracy: 0.8721
Epoch 20/100
14/14 [==============================] - 0s 7ms/step - loss: 0.3328 - accuracy: 0.8630
Epoch 21/100
14/14 [==============================] - 0s 7ms/step - loss: 0.3362 - accuracy: 0.8767
Epoch 22/100
14/14 [==============================] - 0s 9ms/step - loss: 0.3262 - accuracy: 0.8744
Epoch 23/100
14/14 [==============================] - 0s 7ms/step - loss: 0.3263 - accuracy: 0.8767
Epoch 24/100
14/14 [==============================] - 0s 7ms/step - loss: 0.3242 - accuracy: 0.8790
Epoch 25/100
14/14 [==============================] - 0s 7ms/step - loss: 0.3073 - accuracy: 0.8790
Epoch 26/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2839 - accuracy: 0.8904
Epoch 27/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2943 - accuracy: 0.8813
Epoch 28/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2755 - accuracy: 0.8836
Epoch 29/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2943 - accuracy: 0.8858
Epoch 30/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2722 - accuracy: 0.8904
Epoch 31/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2878 - accuracy: 0.8858
Epoch 32/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2932 - accuracy: 0.8836
Epoch 33/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2619 - accuracy: 0.8927
Epoch 34/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2650 - accuracy: 0.8904
Epoch 35/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2618 - accuracy: 0.8973
Epoch 36/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2682 - accuracy: 0.8950
Epoch 37/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2620 - accuracy: 0.9087
Epoch 38/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2666 - accuracy: 0.8973
Epoch 39/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2432 - accuracy: 0.9018
Epoch 40/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2587 - accuracy: 0.9018
Epoch 41/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2477 - accuracy: 0.9041
Epoch 42/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2339 - accuracy: 0.9041
Epoch 43/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2476 - accuracy: 0.9155
Epoch 44/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2496 - accuracy: 0.9178
Epoch 45/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2409 - accuracy: 0.9201
Epoch 46/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2398 - accuracy: 0.9064
Epoch 47/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2458 - accuracy: 0.8995
Epoch 48/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2368 - accuracy: 0.9087
Epoch 49/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2416 - accuracy: 0.9110
Epoch 50/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2313 - accuracy: 0.9110
Epoch 51/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2491 - accuracy: 0.9064
Epoch 52/100
14/14 [==============================] - 0s 8ms/step - loss: 0.2390 - accuracy: 0.8973
Epoch 53/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2332 - accuracy: 0.9110
Epoch 54/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2272 - accuracy: 0.9064
Epoch 55/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2051 - accuracy: 0.9315
Epoch 56/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2310 - accuracy: 0.9041
Epoch 57/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2026 - accuracy: 0.9269
Epoch 58/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2085 - accuracy: 0.9224
Epoch 59/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2169 - accuracy: 0.9247
Epoch 60/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2154 - accuracy: 0.9110
Epoch 61/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2114 - accuracy: 0.9224
Epoch 62/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2201 - accuracy: 0.9178
Epoch 63/100
14/14 [==============================] - 0s 8ms/step - loss: 0.2055 - accuracy: 0.9155
Epoch 64/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2039 - accuracy: 0.9224
Epoch 65/100
14/14 [==============================] - 0s 8ms/step - loss: 0.2183 - accuracy: 0.9224
Epoch 66/100
14/14 [==============================] - 0s 8ms/step - loss: 0.2161 - accuracy: 0.9201
Epoch 67/100
14/14 [==============================] - 0s 8ms/step - loss: 0.1949 - accuracy: 0.9315
Epoch 68/100
14/14 [==============================] - 0s 8ms/step - loss: 0.2007 - accuracy: 0.9292
Epoch 69/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2015 - accuracy: 0.9384
Epoch 70/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1974 - accuracy: 0.9292
Epoch 71/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1993 - accuracy: 0.9178
Epoch 72/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1775 - accuracy: 0.9315
Epoch 73/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1993 - accuracy: 0.9406
Epoch 74/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1854 - accuracy: 0.9338
Epoch 75/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1918 - accuracy: 0.9384
Epoch 76/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1841 - accuracy: 0.9338
Epoch 77/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1789 - accuracy: 0.9338
Epoch 78/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1893 - accuracy: 0.9224
Epoch 79/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1928 - accuracy: 0.9224
Epoch 80/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1936 - accuracy: 0.9224
Epoch 81/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1843 - accuracy: 0.9361
Epoch 82/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1763 - accuracy: 0.9384

Epoch 83/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1798 - accuracy: 0.9269
Epoch 84/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1864 - accuracy: 0.9292
Epoch 85/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1808 - accuracy: 0.9315
Epoch 86/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1639 - accuracy: 0.9429
Epoch 87/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1759 - accuracy: 0.9452
Epoch 88/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1663 - accuracy: 0.9338
Epoch 89/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1844 - accuracy: 0.9269
Epoch 90/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1656 - accuracy: 0.9315
Epoch 91/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1700 - accuracy: 0.9475
Epoch 92/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1585 - accuracy: 0.9384
Epoch 93/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1655 - accuracy: 0.9361
Epoch 94/100
14/14 [==============================] - 0s 8ms/step - loss: 0.1588 - accuracy: 0.9429
Epoch 95/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1584 - accuracy: 0.9406
Epoch 96/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1590 - accuracy: 0.9406
Epoch 97/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1648 - accuracy: 0.9429
Epoch 98/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1640 - accuracy: 0.9475
Epoch 99/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1540 - accuracy: 0.9521
Epoch 100/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1676 - accuracy: 0.9338

In [135]:
model.evaluate(x_test,y_test)

4/4 [==============================] - 0s 32ms/step - loss: 0.2261 - accuracy: 0.9091

[0.2261086404323578, 0.9090909361839294]

In [137]:
model.fit(x,y, epochs=100)

Epoch 1/100
18/18 [==============================] - 0s 9ms/step - loss: 0.1375 - accuracy: 0.9507
Epoch 2/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1374 - accuracy: 0.9489
Epoch 3/100
18/18 [==============================] - 0s 8ms/step - loss: 0.1324 - accuracy: 0.9434
Epoch 4/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1299 - accuracy: 0.9453
Epoch 5/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1455 - accuracy: 0.9526
Epoch 6/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1373 - accuracy: 0.9434
Epoch 7/100
18/18 [==============================] - 0s 8ms/step - loss: 0.1359 - accuracy: 0.9416
Epoch 8/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1218 - accuracy: 0.9562
Epoch 9/100
18/18 [==============================] - 0s 8ms/step - loss: 0.1387 - accuracy: 0.9471
Epoch 10/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1164 - accuracy: 0.9526
Epoch 11/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1327 - accuracy: 0.9526
Epoch 12/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1329 - accuracy: 0.9544
Epoch 13/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1399 - accuracy: 0.9507
Epoch 14/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1303 - accuracy: 0.9489
Epoch 15/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1247 - accuracy: 0.9562
Epoch 16/100
18/18 [==============================] - 0s 9ms/step - loss: 0.1149 - accuracy: 0.9562
Epoch 17/100
18/18 [==============================] - 0s 8ms/step - loss: 0.1196 - accuracy: 0.9471
Epoch 18/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1098 - accuracy: 0.9635
Epoch 19/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1355 - accuracy: 0.9526
Epoch 20/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1313 - accuracy: 0.9453
Epoch 21/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1207 - accuracy: 0.9599
Epoch 22/100
18/18 [==============================] - 0s 8ms/step - loss: 0.1256 - accuracy: 0.9489
Epoch 23/100
18/18 [==============================] - 0s 8ms/step - loss: 0.1334 - accuracy: 0.9471
Epoch 24/100
18/18 [==============================] - 0s 8ms/step - loss: 0.1351 - accuracy: 0.9453
Epoch 25/100
18/18 [==============================] - 0s 8ms/step - loss: 0.1143 - accuracy: 0.9544
Epoch 26/100
18/18 [==============================] - 0s 8ms/step - loss: 0.1215 - accuracy: 0.9544
Epoch 27/100
18/18 [==============================] - 0s 8ms/step - loss: 0.1140 - accuracy: 0.9562
Epoch 28/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1104 - accuracy: 0.9562
Epoch 29/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1129 - accuracy: 0.9580
Epoch 30/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1149 - accuracy: 0.9562
Epoch 31/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1135 - accuracy: 0.9526
Epoch 32/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1231 - accuracy: 0.9562
Epoch 33/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1042 - accuracy: 0.9599
Epoch 34/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1180 - accuracy: 0.9526
Epoch 35/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0958 - accuracy: 0.9653
Epoch 36/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1287 - accuracy: 0.9489
Epoch 37/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1143 - accuracy: 0.9507
Epoch 38/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1166 - accuracy: 0.9580
Epoch 39/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1112 - accuracy: 0.9635
Epoch 40/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1053 - accuracy: 0.9635
Epoch 41/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1196 - accuracy: 0.9526
Epoch 42/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1131 - accuracy: 0.9580
Epoch 43/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1138 - accuracy: 0.9617
Epoch 44/100
18/18 [==============================] - 0s 8ms/step - loss: 0.1326 - accuracy: 0.9562
Epoch 45/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1069 - accuracy: 0.9580
Epoch 46/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0969 - accuracy: 0.9635
Epoch 47/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1094 - accuracy: 0.9562
Epoch 48/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1464 - accuracy: 0.9416
Epoch 49/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1300 - accuracy: 0.9507
Epoch 50/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1059 - accuracy: 0.9653
Epoch 51/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1438 - accuracy: 0.9343
Epoch 52/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1106 - accuracy: 0.9562
Epoch 53/100
18/18 [==============================] - 0s 8ms/step - loss: 0.1178 - accuracy: 0.9526
Epoch 54/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1010 - accuracy: 0.9580
Epoch 55/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0979 - accuracy: 0.9599
Epoch 56/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0882 - accuracy: 0.9690
Epoch 57/100
18/18 [==============================] - 0s 8ms/step - loss: 0.0944 - accuracy: 0.9708
Epoch 58/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0960 - accuracy: 0.9672
Epoch 59/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0906 - accuracy: 0.9653
Epoch 60/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0909 - accuracy: 0.9617
Epoch 61/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0966 - accuracy: 0.9617
Epoch 62/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0938 - accuracy: 0.9653
Epoch 63/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0947 - accuracy: 0.9635
Epoch 64/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0970 - accuracy: 0.9635
Epoch 65/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0918 - accuracy: 0.9653
Epoch 66/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1041 - accuracy: 0.9617
Epoch 67/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0916 - accuracy: 0.9635
Epoch 68/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0892 - accuracy: 0.9635
Epoch 69/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0955 - accuracy: 0.9617
Epoch 70/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1024 - accuracy: 0.9544
Epoch 71/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0941 - accuracy: 0.9599
Epoch 72/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1006 - accuracy: 0.9635
Epoch 73/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0791 - accuracy: 0.9690
Epoch 74/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0851 - accuracy: 0.9745
Epoch 75/100
18/18 [==============================] - 0s 8ms/step - loss: 0.0802 - accuracy: 0.9726
Epoch 76/100
18/18 [==============================] - 0s 8ms/step - loss: 0.0911 - accuracy: 0.9672
Epoch 77/100
18/18 [==============================] - 0s 7ms/step - loss: 0.1019 - accuracy: 0.9562
Epoch 78/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0914 - accuracy: 0.9672
Epoch 79/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0842 - accuracy: 0.9745
Epoch 80/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0950 - accuracy: 0.9580
Epoch 81/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0747 - accuracy: 0.9763
Epoch 82/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0810 - accuracy: 0.9781
Epoch 83/100

18/18 [==============================] - 0s 7ms/step - loss: 0.0957 - accuracy: 0.9653
Epoch 84/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0762 - accuracy: 0.9763
Epoch 85/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0804 - accuracy: 0.9653
Epoch 86/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0934 - accuracy: 0.9690
Epoch 87/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0879 - accuracy: 0.9672
Epoch 88/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0820 - accuracy: 0.9690
Epoch 89/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0808 - accuracy: 0.9690
Epoch 90/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0791 - accuracy: 0.9653
Epoch 91/100
18/18 [==============================] - 0s 8ms/step - loss: 0.0852 - accuracy: 0.9690
Epoch 92/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0765 - accuracy: 0.9708
Epoch 93/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0817 - accuracy: 0.9653
Epoch 94/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0737 - accuracy: 0.9799
Epoch 95/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0978 - accuracy: 0.9653
Epoch 96/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0911 - accuracy: 0.9635
Epoch 97/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0838 - accuracy: 0.9708
Epoch 98/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0682 - accuracy: 0.9763
Epoch 99/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0779 - accuracy: 0.9708
Epoch 100/100
18/18 [==============================] - 0s 7ms/step - loss: 0.0830 - accuracy: 0.9653

In [142]:
x.head()

,AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD,...,FL,FR,FS,GB,GE,GF,GH,GI,GL,EJ_A
0,0.028487,0.102347,0.00000,0.030632,0.0,0.000000,0.000000,0.180337,0.002958,0.047364,...,0.051720,0.000998,0.000866,0.049385,0.000000,0.013846,0.176983,0.362261,0.005425,0
1,0.013752,0.027589,0.00000,0.053864,0.0,0.078048,0.000000,0.284500,0.000000,0.074042,...,0.000000,0.000000,0.016014,0.033753,0.000000,0.194527,0.274495,0.164135,1.000000,1
2,0.088409,0.085715,0.00000,0.046519,0.0,0.160575,0.000000,0.265013,0.000000,0.067011,...,0.054706,0.000385,0.036139,0.246003,0.011229,0.095035,0.258994,0.180218,0.008910,0
3,0.038310,0.127285,0.01918,0.117854,0.0,0.079462,0.000000,0.215235,0.000000,0.048203,...,0.043183,0.000000,0.006925,0.104313,0.006882,0.014475,0.425143,0.470820,0.007039,0
4,0.067780,0.124246,0.00000,0.017417,0.0,0.086300,0.002841,0.000000,0.069008,0.078555,...,0.057926,0.038597,0.001731,0.088112,0.051588,0.059198,0.500829,0.185841,0.004345,0

In [146]:
df_test_phase2

,Id,AB,AF,AH,AM,AR,AX,AY,AZ,BC,...,FL,FR,FS,GB,GE,GF,GH,GI,GL,EJ_A
0,00eed32682bb,-0.019646,-0.006759,-0.046687,-0.005065,-0.047649,-0.018628,-0.002486,-0.095483,-0.000841,...,-0.001257,-0.0004,-0.002164,-0.037234,-0.050964,-0.000091,-0.131415,-0.004717,-0.000051,1
1,010ebe33f668,-0.019646,-0.006759,-0.046687,-0.005065,-0.047649,-0.018628,-0.002486,-0.095483,-0.000841,...,-0.001257,-0.0004,-0.002164,-0.037234,-0.050964,-0.000091,-0.131415,-0.004717,-0.000051,1
2,02fa521e1838,-0.019646,-0.006759,-0.046687,-0.005065,-0.047649,-0.018628,-0.002486,-0.095483,-0.000841,...,-0.001257,-0.0004,-0.002164,-0.037234,-0.050964,-0.000091,-0.131415,-0.004717,-0.000051,1
3,040e15f562a2,-0.019646,-0.006759,-0.046687,-0.005065,-0.047649,-0.018628,-0.002486,-0.095483,-0.000841,...,-0.001257,-0.0004,-0.002164,-0.037234,-0.050964,-0.000091,-0.131415,-0.004717,-0.000051,1
4,046e85c7cc7f,-0.019646,-0.006759,-0.046687,-0.005065,-0.047649,-0.018628,-0.002486,-0.095483,-0.000841,...,-0.001257,-0.0004,-0.002164,-0.037234,-0.050964,-0.000091,-0.131415,-0.004717,-0.000051,1

In [144]:
df_test_phase3 = df_test_phase2.drop(['Id'], axis=1)

In [148]:
pred = model.predict(df_test_phase3)
last = pd.DataFrame(pred, columns=['Prediction'])
last.head()

1/1 [==============================] - 0s 14ms/step

   Prediction
0    0.910992
1    0.910992
2    0.910992
3    0.910992
4    0.910992

In [152]:
import numpy as np
last['class_0'] = np.where(last['Prediction']>=0.5, 0, 1)
last['class_1'] = np.where(last['Prediction']>=0.5, 1, 0)
last['Id'] = df_test_phase2['Id']
last.head()

   Prediction  pred  class_0  class_1            Id
0    0.910992     1        0        1  00eed32682bb
1    0.910992     1        0        1  010ebe33f668
2    0.910992     1        0        1  02fa521e1838
3    0.910992     1        0        1  040e15f562a2
4    0.910992     1        0        1  046e85c7cc7f

In [153]:
last.drop(['Prediction','pred'], axis=1, inplace=True)

In [155]:
last.to_csv('./data/predicted.csv')